# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ef3Hndp7Poj-5WbUfqk1_oASQ7IK7WnX
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# ML & Prophet
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import xgboost as xgb
from prophet import Prophet
import joblib

plt.style.use('seaborn-v0_8')

# Load Data
data = pd.read_csv("/content/sales_06_FY2020-21 copy.csv")
print("Shape:", data.shape)
print("Columns:", data.columns.tolist())
data.head()

# Convert date
data['order_date'] = pd.to_datetime(data['order_date'], errors='coerce')

# Drop rows with missing critical values
data = data.dropna(subset=['order_date', 'User Name', 'category', 'price', 'qty_ordered'])

# Revenue Calculation
data['revenue'] = data['qty_ordered'] * data['price']

# Additional Features
data['discount_rate'] = data['discount_amount'] / data['value'].replace(0, 1)
data['is_discounted'] = (data['discount_amount'] > 0).astype(int)
data['month'] = data['order_date'].dt.month
data['dayofweek'] = data['order_date'].dt.dayofweek
data['price_per_unit'] = data['price']

print("Cleaned Shape:", data.shape)
data.info()

latest_date = data['order_date'].max()

rfm = data.groupby('User Name').agg({
    'order_date': lambda x: (latest_date - x.max()).days,
    'order_id': 'count',
    'revenue': 'sum'
}).rename(columns={
    'order_date': 'Recency',
    'order_id': 'Frequency',
    'revenue': 'Monetary'
})

# Outlier Removal
rfm = rfm[rfm['Monetary'] < rfm['Monetary'].quantile(0.99)]

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency', 'Frequency', 'Monetary']])

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

segment_map = {0: 'Loyal', 1: 'VIP', 2: 'Lost', 3: 'Regular'}
rfm['Segment'] = rfm['Cluster'].map(segment_map)

print(rfm['Segment'].value_counts())
rfm.head()

rfm.groupby('Cluster')[['Recency','Frequency','Monetary']].mean()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=rfm.reset_index(), x='Recency', y='Monetary',
                hue='Segment', size='Frequency', palette='viridis')
plt.title('RFM Customer Segments')
plt.show()

monthly = data.groupby(data['order_date'].dt.to_period('M'))['revenue'].sum().reset_index()
monthly['ds'] = monthly['order_date'].dt.to_timestamp()
monthly = monthly.rename(columns={'revenue': 'y'}).drop(columns=['order_date'])

model = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)
model.fit(monthly)

future = model.make_future_dataframe(periods=6, freq='M')
forecast = model.predict(future)

model.plot(forecast)
plt.title('Revenue Forecast - Next 6 Months')
plt.show()

model.plot_components(forecast)
plt.show()

pred_data = data.copy()

# Strong Feature Engineering
pred_data['revenue'] = pred_data['qty_ordered'] * pred_data['price']
pred_data['discount_rate'] = pred_data['discount_amount'] / pred_data['value'].replace(0, 1)
pred_data['is_discounted'] = (pred_data['discount_amount'] > 0).astype(int)
pred_data['month'] = pred_data['order_date'].dt.month
pred_data['dayofweek'] = pred_data['order_date'].dt.dayofweek

# SKU Features
pred_data['sku'] = pred_data['sku'].astype(str)
pred_data['sku_prefix'] = pred_data['sku'].str[:6]
pred_data['sku_prefix2'] = pred_data['sku'].str[:4]
pred_data['sku_contains_me'] = pred_data['sku'].str.contains('MEF|ME', case=False, na=False).astype(int)
pred_data['sku_contains_mat'] = pred_data['sku'].str.contains('MAT', case=False, na=False).astype(int)
pred_data['sku_contains_wof'] = pred_data['sku'].str.contains('WOF', case=False, na=False).astype(int)
pred_data['sku_contains_app'] = pred_data['sku'].str.contains('APP', case=False, na=False).astype(int)

# Price & Quantity Bins
pred_data['price_range'] = pd.qcut(pred_data['price'], q=10, duplicates='drop', labels=False)
pred_data['qty_range'] = pd.qcut(pred_data['qty_ordered'], q=8, duplicates='drop', labels=False)

# Encoding
le = LabelEncoder()
pred_data['category_encoded'] = le.fit_transform(pred_data['category'])

# Final Features List
features = ['price', 'qty_ordered', 'value', 'discount_amount', 'revenue', 'discount_rate',
            'is_discounted', 'month', 'dayofweek', 'price_range', 'qty_range',
            'sku_contains_me', 'sku_contains_mat', 'sku_contains_wof', 'sku_contains_app']

X = pred_data[features]
y = pred_data['category_encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# XGBoost Final
xgb_model = xgb.XGBClassifier(
    n_estimators=1000,
    max_depth=16,
    learning_rate=0.06,
    subsample=0.85,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='mlogloss',
    n_jobs=-1,
    tree_method='hist'
)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

print(" FINAL XGBoost Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))

# Feature Importance
importances = pd.Series(xgb_model.feature_importances_, index=features).sort_values(ascending=False)
print("\n Top Features:\n", importances.head(15))

import joblib
from prophet.serialize import model_to_json

# Save KMeans
joblib.dump(kmeans, 'kmeans_rfm.pkl')

# Save XGBoost
joblib.dump(xgb_model, 'product_category_xgb.pkl')

# Save Prophet Model
with open('prophet_revenue_model.json', 'w') as f:
    f.write(model_to_json(model))

print(" All models saved successfully")
print("   • kmeans_rfm.pkl")
print("   • product_category_xgb.pkl")
print("   • prophet_revenue_model.json")